/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as AuthedRouteImport } from "./routes/_authed.tsx";
import { Route as LoginRouteImport } from "./routes/login.tsx";
import { Route as SetupRouteImport } from "./routes/setup.tsx";
import { Route as AuthedIndexRouteImport } from "./routes/_authed/index.tsx";
import { Route as AuthedPrintersNewRouteImport } from "./routes/_authed/printers/new.tsx";
import { Route as AuthedPrintersPrinterIdIndexRouteImport } from "./routes/_authed/printers/$printerId/index.tsx";
import { Route as AuthedPrintersPrinterIdEditRouteImport } from "./routes/_authed/printers/$printerId/edit.tsx";

const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedPrintersNewRoute = AuthedPrintersNewRouteImport.update({
  id: "/printers/new",
  path: "/printers/new",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedPrintersPrinterIdIndexRoute =
  AuthedPrintersPrinterIdIndexRouteImport.update({
    id: "/printers/$printerId/",
    path: "/printers/$printerId/",
    getParentRoute: () => AuthedRoute,
  } as any);
const AuthedPrintersPrinterIdEditRoute =
  AuthedPrintersPrinterIdEditRouteImport.update({
    id: "/printers/$printerId/edit",
    path: "/printers/$printerId/edit",
    getParentRoute: () => AuthedRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthedIndexRoute;
  "/login": typeof LoginRoute;
  "/setup": typeof SetupRoute;
  "/printers/new": typeof AuthedPrintersNewRoute;
  "/printers/$printerId/edit": typeof AuthedPrintersPrinterIdEditRoute;
  "/printers/$printerId/": typeof AuthedPrintersPrinterIdIndexRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/setup": typeof SetupRoute;
  "/": typeof AuthedIndexRoute;
  "/printers/new": typeof AuthedPrintersNewRoute;
  "/printers/$printerId/edit": typeof AuthedPrintersPrinterIdEditRoute;
  "/printers/$printerId": typeof AuthedPrintersPrinterIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authed": typeof AuthedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/setup": typeof SetupRoute;
  "/_authed/": typeof AuthedIndexRoute;
  "/_authed/printers/new": typeof AuthedPrintersNewRoute;
  "/_authed/printers/$printerId/edit": typeof AuthedPrintersPrinterIdEditRoute;
  "/_authed/printers/$printerId/": typeof AuthedPrintersPrinterIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/setup"
    | "/printers/new"
    | "/printers/$printerId/edit"
    | "/printers/$printerId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/setup"
    | "/"
    | "/printers/new"
    | "/printers/$printerId/edit"
    | "/printers/$printerId";
  id:
    | "__root__"
    | "/_authed"
    | "/login"
    | "/setup"
    | "/_authed/"
    | "/_authed/printers/new"
    | "/_authed/printers/$printerId/edit"
    | "/_authed/printers/$printerId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SetupRoute: typeof SetupRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/setup": {
      id: "/setup";
      path: "/setup";
      fullPath: "/setup";
      preLoaderRoute: typeof SetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/": {
      id: "/_authed/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthedIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/printers/new": {
      id: "/_authed/printers/new";
      path: "/printers/new";
      fullPath: "/printers/new";
      preLoaderRoute: typeof AuthedPrintersNewRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/printers/$printerId/": {
      id: "/_authed/printers/$printerId/";
      path: "/printers/$printerId";
      fullPath: "/printers/$printerId/";
      preLoaderRoute: typeof AuthedPrintersPrinterIdIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/printers/$printerId/edit": {
      id: "/_authed/printers/$printerId/edit";
      path: "/printers/$printerId/edit";
      fullPath: "/printers/$printerId/edit";
      preLoaderRoute: typeof AuthedPrintersPrinterIdEditRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute;
  AuthedPrintersNewRoute: typeof AuthedPrintersNewRoute;
  AuthedPrintersPrinterIdEditRoute: typeof AuthedPrintersPrinterIdEditRoute;
  AuthedPrintersPrinterIdIndexRoute: typeof AuthedPrintersPrinterIdIndexRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPrintersNewRoute: AuthedPrintersNewRoute,
  AuthedPrintersPrinterIdEditRoute: AuthedPrintersPrinterIdEditRoute,
  AuthedPrintersPrinterIdIndexRoute: AuthedPrintersPrinterIdIndexRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
