// SPDX-FileCopyrightText: 2026 Open Print Stack contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

import path from "node:path";

import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { readMigrationFiles } from "drizzle-orm/migrator";

import type { Logger } from "../logger.ts";
import type { Db } from "./client.ts";

/** The committed migrations, generated by drizzle-kit from schema.ts. */
export const MIGRATIONS_FOLDER = path.join(
  import.meta.dirname,
  "../../drizzle",
);

/** Where Drizzle records the migrations it has applied. */
const MIGRATIONS_TABLE = "__drizzle_migrations";

/** The database was migrated by a newer version of the server. */
export class DatabaseTooNewError extends Error {
  constructor(file: string) {
    super(
      `${file} was updated by a newer version of Open Print Stack, so this version can't use it. Run the newer version, or restore a backup.`,
    );
    this.name = "DatabaseTooNewError";
  }
}

/**
 * Applies any migrations the database hasn't had yet, all in one transaction.
 * Refuses a database that a newer server has migrated: Drizzle on its own
 * would carry on with a schema this version doesn't understand.
 */
export function migrateDatabase(
  db: Db,
  logger: Logger,
  migrationsFolder: string = MIGRATIONS_FOLDER,
): void {
  const log = logger.child({ component: "db" });
  // Drizzle orders migrations by the time drizzle-kit generated each one.
  const newestKnown = Math.max(
    ...readMigrationFiles({ migrationsFolder }).map((m) => m.folderMillis),
  );

  const before = appliedMigrations(db);
  if (before.newest !== null && before.newest > newestKnown) {
    throw new DatabaseTooNewError(db.$client.name);
  }

  migrate(db, { migrationsFolder, migrationsTable: MIGRATIONS_TABLE });

  const applied = appliedMigrations(db).count - before.count;
  if (applied > 0) {
    log.info({ applied }, "Applied database migrations");
  } else {
    log.debug("Database schema is up to date");
  }
}

function appliedMigrations(db: Db): { count: number; newest: number | null } {
  const sqlite = db.$client;
  const table: unknown = sqlite
    .prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?")
    .pluck()
    .get(MIGRATIONS_TABLE);
  if (table === undefined) return { count: 0, newest: null };
  const row = sqlite
    .prepare(
      `SELECT count(*) AS count, max(created_at) AS newest FROM ${MIGRATIONS_TABLE}`,
    )
    .get() as { count: number; newest: number | null };
  return {
    count: row.count,
    newest: row.newest === null ? null : Number(row.newest),
  };
}
